---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/R/R.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/1327/articles/278681/master/folder/figures/R"
    url: "/users/1327/articles/278681/master/file/figures/R/R.png"
